name: Deploy to server

on:
  push:
    tags:
      - 'deploy-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            cd /usr/src/marketing-bot
            git pull

      - name: Upload Google credentials.json
        uses: appleboy/ssh-action@v1
        env:
          GCP_SHEETS_JSON_B64: ${{ secrets.GCP_SHEETS_JSON_B64 }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT || 22 }}
          envs: GCP_SHEETS_JSON_B64
          script: |
            cd /usr/src/marketing-bot
            echo "$GCP_SHEETS_JSON_B64" | base64 -d > google-credentials.json

      - name: Build image
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            cd /usr/src/marketing-bot
            docker build -f ./Dockerfile . --tag marketing-bot:latest

      - name: Docker compose start
        uses: appleboy/ssh-action@v1
        env:
          API_HASH: ${{ secrets.API_HASH }}
          API_ID: ${{ secrets.API_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          LOGGING_CHAT_ID: ${{ secrets.LOGGING_CHAT_ID }}
          PARSER_CHAT_ID: ${{ secrets.PARSER_CHAT_ID }}
          PARSER_CHAT_ALL_MESSAGES_ID: ${{ secrets.PARSER_CHAT_ALL_MESSAGES_ID }}
          PARSER_VK_CHAT_ID: ${{ secrets.PARSER_VK_CHAT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT || 22 }}
          envs: API_HASH, API_ID, BOT_TOKEN, LOGGING_CHAT_ID, PARSER_CHAT_ID, PARSER_CHAT_ALL_MESSAGES_ID, PARSER_VK_CHAT_ID, OPENAI_API_KEY
          script: |
            cd /usr/src/marketing-bot
            docker compose down
            export API_HASH="$API_HASH"
            export API_ID="$API_ID"
            export BOT_TOKEN="$BOT_TOKEN"
            export LOGGING_CHAT_ID="$LOGGING_CHAT_ID"
            export PARSER_CHAT_ID="$PARSER_CHAT_ID"
            export PARSER_CHAT_ALL_MESSAGES_ID="$PARSER_CHAT_ALL_MESSAGES_ID"
            export PARSER_VK_CHAT_ID="$PARSER_VK_CHAT_ID"
            export OPENAI_API_KEY="$OPENAI_API_KEY"
            docker compose up -d
